name: computeiro
description: A new Flutter project.
version: 1.1.5+15

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  scoped_model: ^1.1.0
  flutter_tex: ^3.6.7+10
  flutter_downloader: ^1.5.1
  path_provider: ^1.6.21
  permission_handler: ^5.0.1+1
  firebase_core: ^0.5.0+1
  firebase_analytics: ^6.0.2
  url_launcher: ^5.7.5
  share: ^0.6.5+3
  flutter_svg: ^0.19.0
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  flutter_driver:
    sdk: flutter
  test: any

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/computeiro.png'
  adaptive_icon_background: '#FFFAFAFA'
  adaptive_icon_foreground: 'assets/icon/computeiro.png'

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
