name: computeiro
description: A new Flutter project.
version: 1.1.2+9

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_markdown: ^0.2.0
  http: ^0.12.0+1
  scoped_model: ^1.0.1
  flutter_tex: ^1.0.0
  flutter_downloader: ^1.1.7
  path_provider: ^1.1.0
  permission_handler: ^3.1.0
  firebase_core: ^0.3.4
  firebase_analytics: ^2.1.1+1
  firebase_admob: ^0.8.0+3
  url_launcher: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  flutter_driver:
    sdk: flutter
  test: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/computeiro.png"
  adaptive_icon_background: "#FFFAFAFA"
  adaptive_icon_foreground: "assets/icon/computeiro.png"

flutter:
  uses-material-design: true
