name: computeiro
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_markdown: ^0.2.0
  http: ^0.12.0+1
  scoped_model: ^1.0.1
  flutter_tex: ^0.0.15
  flutter_downloader: ^1.1.6
  path_provider: ^0.5.0+1
  permission_handler: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/computeiro.png"
  adaptive_icon_background: "#FFFAFAFA"
  adaptive_icon_foreground: "assets/icon/computeiro.png"

flutter:
  uses-material-design: true
