name: computeiro
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_markdown: ^0.2.0
  flutter_redux: ^0.5.3
  redux_epics: ^0.10.3
  http: ^0.12.0+1
  # fluttertoast: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
